export const evangelismData = [
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Cynthia Oluebubechukwu",
    phoneNumber: "555-123-4567",
    sex: "Female",
    assignedWorker: "Pastor Michael",
    contacted: true,
    feedback: "Enjoyed the service, interested in learning more",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Falilat Olasunbo",
    phoneNumber: "555-987-6543",
    sex: "Female",
    assignedWorker: "Deacon James",
    contacted: true,
    feedback: "Had many questions about faith, wants to attend Sunday service",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ugochi Onyearugha",
    phoneNumber: "555-456-7890",
    sex: "Female",
    assignedWorker: "Sister Rachel",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Elizabeth Obeya",
    phoneNumber: "555-234-5678",
    sex: "Female",
    assignedWorker: "Brother Thomas",
    contacted: true,
    feedback: "Very receptive, attended prayer meeting",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Osinachi Otti",
    phoneNumber: "555-345-6789",
    sex: "Female",
    assignedWorker: "Sister Hannah",
    contacted: true,
    feedback: "Interested in volunteer opportunities",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Adeshola Adenusi",
    phoneNumber: "555-456-7891",
    sex: "Female",
    assignedWorker: "Pastor David",
    contacted: true,
    feedback: "Brought family to Sunday service",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Victoria Ubah",
    phoneNumber: "555-567-8912",
    sex: "Female",
    assignedWorker: "Deacon Peter",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Olamide Abdul",
    phoneNumber: "555-678-9123",
    sex: "Female",
    assignedWorker: "Sister Mary",
    contacted: true,
    feedback: "Enthusiastic about joining regular Bible study",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ogar Solomon",
    phoneNumber: "555-789-0123",
    sex: "Male",
    assignedWorker: "Brother Joseph",
    contacted: true,
    feedback: "Seeking guidance for personal issues",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Chinyere",
    phoneNumber: "555-890-1234",
    sex: "Female",
    assignedWorker: "Sister Elizabeth",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Blessing Nuru",
    phoneNumber: "555-901-2345",
    sex: "Female",
    assignedWorker: "Pastor Jonathan",
    contacted: true,
    feedback: "Interested in youth program for children",
    foundationClass: true,
    counselingClass: false,
  },
];

export const alterCall = [
  {
    dateOfVisit: "14-Feb-2025",
    churchProgram: "Sunday Service",
    name: "Jimmy Grace Ejiro",
    phoneNumber: "09022770492",
    sex: "Female",
    assignedWorker: "Sis Eucharia",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    foundationClass: true,
    counselingClass: false,
  },
];
