export const evangelismData = [
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Falilat Olasunbo",
    phoneNumber: "08170360096",
    sex: "Female",
    assignedWorker: "Sis Wande",
    contacted: true,
    feedback: "hu",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ugochi Onyearugha",
    phoneNumber: "07036472276",
    sex: "Female",
    assignedWorker: "Sis Wande",
    contacted: true,
    feedback: "",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Elizabeth Obeya",
    phoneNumber: "08107233128",
    sex: "Female",
    assignedWorker: "Sis Eucharia",
    contacted: true,
    feedback: "",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Osinachi Otti",
    phoneNumber: "09043175037",
    sex: "Female",
    assignedWorker: "Sis Eucharia",
    contacted: true,
    feedback: "",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Adeshola Adenusi",
    phoneNumber: "NA",
    sex: "Male",
    assignedWorker: "Sis Eucharia",
    contacted: true,
    feedback: "",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Victoria Ubah",
    phoneNumber: "09065883109",
    sex: "Female",
    assignedWorker: "Prof Lara",
    contacted: true,
    feedback: "Not available to attend church",
    feedback2: "God's protection for her and her children.",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Olamide Abdul",
    phoneNumber: "07084746398",
    sex: "Male",
    assignedWorker: "Prof Lara",
    contacted: false,
    feedback: "Not available to attend church",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ogar Solomon",
    phoneNumber: "08069226265",
    sex: "Male",
    assignedWorker: "Prof Lara",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Chinyere",
    phoneNumber: "08064691339",
    sex: "Female",
    assignedWorker: "Bro Charles",
    contacted: false,
    feedback: "Other reasons",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Blessing Nuru",
    phoneNumber: "09133989216",
    sex: "Female",
    assignedWorker: "Bro Charles",
    contacted: false,
    feedback: "Other reasons",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Malachy",
    phoneNumber: "08060738290",
    sex: "Male",
    assignedWorker: "Bro Charles",
    contacted: true,
    feedback: "Worships at another church",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Lazarus",
    phoneNumber: "09030321274",
    sex: "Male",
    assignedWorker: "Bro Charles",
    contacted: false,
    feedback: "Other reasons",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Afolabi Oluwatosin",
    phoneNumber: "08059298485",
    sex: "Female",
    assignedWorker: "Bro Charles",
    contacted: true,
    feedback: "Line not reachable/switched off",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Moshood",
    phoneNumber: "08022763848",
    sex: "Male",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Jennifer",
    phoneNumber: "08121706625",
    sex: "Female",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Wisdom",
    phoneNumber: "09055701160",
    sex: "Male",
    assignedWorker: "Bro Laju",
    contacted: true,
    feedback: "Appreciate us calling him, follows GO online, Born Again",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ndum Carine",
    phoneNumber: "08025924280",
    sex: "Female",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Joseph Ogbu",
    phoneNumber: "08103429391",
    sex: "Male",
    assignedWorker: "Bro Laju",
    contacted: true,
    feedback: "Born Again, attends Redeem",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Omodele Abayomi",
    phoneNumber: "07030181562",
    sex: "Male",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "Divine intervention",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Abraham",
    phoneNumber: "08082068051",
    sex: "Female",
    assignedWorker: "Sis Modupe",
    contacted: false,
    feedback: "Line not reachable/switched off",
    feedback2: "I sent text since her number was not reachable.",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Thomas",
    phoneNumber: "07066153346",
    sex: "Male",
    assignedWorker: "Sis Modupe",
    contacted: true,
    feedback:
      "His number will ring once and then give me an engaging tone. His message was returned.",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Crystabel",
    phoneNumber: "09049838272",
    sex: "Female",
    assignedWorker: "Sis Modupe",
    contacted: false,
    feedback: "Line not reachable/switched off",
    feedback2: "sent text since her number was not reachable",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Abiodun Olubunkola",
    phoneNumber: "07063766061",
    sex: "Female",
    assignedWorker: "Sis Modupe",
    contacted: true,
    feedback: "Worships at another church",
    feedback2: "She has joined another MFM church closer to her",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Comfort Joshua",
    phoneNumber: "09166963326",
    sex: "Female",
    assignedWorker: "Sis Modupe",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback2:
      "She will call me tomorrow if she will be attending or join mid week service",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Mr. Ayo",
    phoneNumber: "07064679612",
    sex: "Male",
    assignedWorker: "Sis Oyin",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ayo",
    phoneNumber: "08160838194",
    sex: "Female",
    assignedWorker: "Sis Oyin",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Mr.Ola",
    phoneNumber: "08066875007",
    sex: "Male",
    assignedWorker: "Sis Oyin",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Mr.Moses",
    phoneNumber: "09023169946",
    sex: "Male",
    assignedWorker: "Sis Ekene",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Salome",
    phoneNumber: "08087870897",
    sex: "Female",
    assignedWorker: "Sis Ekene",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ruth",
    phoneNumber: "09042473450",
    sex: "Female",
    assignedWorker: "Sis Folashade",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Oluseyi",
    phoneNumber: "08171686876",
    sex: "Male",
    assignedWorker: "Sis Folashade",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Gabriel",
    phoneNumber: "07038950935",
    sex: "Male",
    assignedWorker: "Sis Lara",
    contacted: true,
    feedback: "Other reasons",
    feedback2:
      "Requested that we continue to pray for God's favour. He does not have money to come to church and he will rather join the service online.",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Lucky",
    phoneNumber: "08056270223",
    sex: "Male",
    assignedWorker: "Sis Lara",
    contacted: true,
    feedback: "Not available to attend church",
    feedback:
      "Prayer request, God should bless his business. Promised to worship with us anytime he is around.",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Kehinde",
    phoneNumber: "09029034132",
    sex: "",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Bisola",
    phoneNumber: "08105172461",
    sex: "",
    assignedWorker: "Bro Laju",
    contacted: true,
    feedback: "Prayer of Mercy and Blessings",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Janet",
    phoneNumber: "09045609887",
    sex: "",
    assignedWorker: "Bro Laju",
    contacted: true,
    feedback: "She is a believer, God should bless her, family and business",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Yusuf",
    phoneNumber: "09029553279",
    sex: "",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Johnson",
    phoneNumber: "07059811603",
    sex: "",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Afin",
    phoneNumber: "07087726045",
    sex: "",
    assignedWorker: "Prof Lara",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Isaac",
    phoneNumber: "08038166722",
    sex: "",
    assignedWorker: "Prof Lara",
    contacted: true,
    feedback: "Line not reachable/switched off",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Mattew",
    phoneNumber: "08121121106",
    sex: "",
    assignedWorker: "Bro Charles",
    feedback: "Line not reachable/switched off",
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Wale & Ishola & Ademola",
    phoneNumber: "07069057734",
    sex: "",
    assignedWorker: "Bro Charles",
    contacted: true,
    feedback: "Other reasons",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Donald Atim",
    phoneNumber: "09052587459",
    sex: "",
    assignedWorker: "Bro Charles",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Sunday John",
    phoneNumber: "08064273405",
    sex: "",
    assignedWorker: "Sis Lara",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Micheal Paul",
    phoneNumber: "09074532704",
    sex: "Male"
    assignedWorker: "Sis Lara",
    contacted: true,
    feedback: "Not available to attend church",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "David Lawrence",
    phoneNumber: "08070940592",
    sex: "",
    assignedWorker: "Sis Folashade",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Abdul",
    phoneNumber: "08120200279",
    sex: "",
    assignedWorker: "Sis Folashade",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Peace",
    phoneNumber: "09022856141",
    sex: "",
    assignedWorker: "Sis Wande",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Peter",
    phoneNumber: "08082587873",
    sex: "",
    assignedWorker: "Sis Wande",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "John",
    phoneNumber: "08162341004",
    sex: "",
    assignedWorker: "Sis Modupe",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Daniel",
    phoneNumber: "09161684483",
    sex: "Male",
    assignedWorker: "Sis Modupe",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback:
      "He will come to church tomorrow and was very delighted about us calling him to check up on him",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Godfrey",
    phoneNumber: "08135453742",
    sex: "",
    assignedWorker: "Sis Eucharia",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Manasseh",
    phoneNumber: "07070755867",
    sex: "",
    assignedWorker: "Sis Eucharia",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Paul Okafor",
    phoneNumber: "08068336568",
    sex: "Male",
    assignedWorker: "Sis Ekene",
    contacted: false,
    feedback: "",
    foundationClass: true,
    counselingClass: true,
  },
];

export const alterCall = [
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Otosi Joseph Martins",
    phoneNumber: "09013263605",
    phoneNumber2: "07031980909",
    sex: "",
    assignedWorker: "Bro Charles",
    contacted: false,
    feedback: "Line not reachable/switched off",
    feedback2:"Line not reachable/switched off",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Aleju Johnson Igoh",
    phoneNumber: "09054640243",
    sex: "Male",
    assignedWorker: "Bro Charles",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback2:"Has done Foundation Class and is just waiting to write the exam",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Faith Oriabor",
    phoneNumber: "07084578949",
    sex: "Female",
    assignedWorker: "Sis Folashade",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback2:"will go for deliverance first and will consider the Foundation class aftewrward",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Samuel Godgrace",
    phoneNumber: "08033846546",
    sex: "Female",
    assignedWorker: "Sis Lara",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback2:"Ready to commence Foundation class this Sunday (16 February)",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Jimmy Grace Ejiro",
    phoneNumber: "09022770492",
    sex: "Female",
    assignedWorker: "Sis Eucharia",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback2:"Will be in church today and will like to join deliverance session ",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Ochieja Elizabeth Chinyere",
    phoneNumber: "09077743887",
    phoneNumber2: "08179849061",
    sex: "Female",
    assignedWorker: "Sis Eucharia",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Uzoma Chikamso Rita",
    phoneNumber: "07082958098",
    sex: "Female",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "John",
    phoneNumber: "09027758924",
    sex: "",
    assignedWorker: "Sis Wande",
    contacted: false,
    feedback: "Line not reachable/switched off",
    feedback2:"Line does not exist",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Light Omozele Stephen",
    phoneNumber: "08158010210",
    sex: "Male",
    assignedWorker: "Sis Wande",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback2:"Will join the Foundation class tommorow 16 February",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Okafor Chidiebube",
    phoneNumber: "09074264132",
    sex: "Male",
    assignedWorker: "Bro Charles",
    contacted: false,
    feedback: "Line not reachable/switched off",
    feedback2:"Line not reachable/switched off",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Mattias Orubi",
    phoneNumber: "",
    sex: "",
    assignedWorker: "Bro Charles",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Uchechi Caroline o",
    phoneNumber: "08164259111",
    sex: "Female",
    assignedWorker: "Bro Charles",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback2:"Will be visiting us on Sunday",
     foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Ufele Joy Nneka",
    phoneNumber: "08071679039",
    sex: "Female",
    assignedWorker: "Sis Modupe",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback: "Interested",
     foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Mercy Genesis",
    phoneNumber: "08104129288",
    sex: "",
    assignedWorker: "Sis Modupe",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Dejinu Matthew",
    phoneNumber: "08027436695",
    sex: "Male",
    assignedWorker: "Sis Modupe",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Heri Ishiyah Donatus",
    phoneNumber: "08086052444",
    sex:"Female",
    assignedWorker: "Sis Wande",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Achadu Blessing",
    phoneNumber: "08102164243",
    sex: "",
    assignedWorker: "Sis Wande",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Ayedun Oriyomi Salmat",
    phoneNumber: "09112365226",
     sex: "Female",
    assignedWorker: "Sis Wande",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Ajie Gloria Yeoni",
    phoneNumber: "07048400764",
     sex: "Female",
    assignedWorker: "Sis Lara",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Mrs Yetunde Olarenwaju",
    phoneNumber: "08020549261",
    sex: "Female",
    assignedWorker: "Sis Lara",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Online Convert",
    name: "Tolulope - Canada",
    phoneNumber: "08171405602",
    sex: "",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "Line not reachable/switched off",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Online Convert",
    name: "Felicia Onyema - Italy",
    phoneNumber: "+393512918889",
    sex: "Female",
    assignedWorker: "Bro Laju",
    contacted: true,
    feedback: "Out of the city",
    feedback2:"Open to personal counselling",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Online Convert",
    name: "Ojochebo Ogbadu - Abuja",
    phoneNumber: "09044777350",
    sex: "",
    assignedWorker: "Bro Laju",
    contacted: true,
    feedback: "Out of the city",
    feedback2:"Resides in Abuja, attends a bible believing church, will confirm if open to personal counselling",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Online Convert",
    name: "Mary Olabisi Ogunbiyi - Lagos",
    phoneNumber: "09075582354",
    sex: "",
    assignedWorker: "Bro Laju",
    contacted: true,
    feedback: "Will be visiting us on Sunday",
    feedback2:"Aware of Foundation class, attends our Sunday service",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Ngozi",
    phoneNumber: "07063709290",
    sex: "",
    assignedWorker: "Bro Laju",
     contacted: false,
     feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Onwuna Janet",
    phoneNumber: "09121123913",
    sex: "",
    assignedWorker: "Bro Laju",
     contacted: false,
     feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "5-Jan-2025",
    churchProgram: "Sunday Service",
    name: "Mr Leonard Jude",
    phoneNumber: "09014458888",
    sex: "Male",
    assignedWorker: "Bro Laju",
    contacted: false,
    feedback: "",
    feedback2:"Number does not exit",
    foundationClass: false,
    counselingClass: false,
  },
];
