export const evangelismData = [
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Cynthia Oluebubechukwu",
    phoneNumber: "555-123-4567",
    sex: "Female",
    assignedWorker: "Pastor Michael",
    contacted: true,
    feedback: "Enjoyed the service, interested in learning more",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Falilat Olasunbo",
    phoneNumber: "555-987-6543",
    sex: "Female",
    assignedWorker: "Deacon James",
    contacted: true,
    feedback: "Had many questions about faith, wants to attend Sunday service",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ugochi Onyearugha",
    phoneNumber: "555-456-7890",
    sex: "Female",
    assignedWorker: "Sister Rachel",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Elizabeth Obeya",
    phoneNumber: "555-234-5678",
    sex: "Female",
    assignedWorker: "Brother Thomas",
    contacted: true,
    feedback: "Very receptive, attended prayer meeting",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Osinachi Otti",
    phoneNumber: "555-345-6789",
    sex: "Female",
    assignedWorker: "Sister Hannah",
    contacted: true,
    feedback: "Interested in volunteer opportunities",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Adeshola Adenusi",
    phoneNumber: "555-456-7891",
    sex: "Female",
    assignedWorker: "Pastor David",
    contacted: true,
    feedback: "Brought family to Sunday service",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Victoria Ubah",
    phoneNumber: "555-567-8912",
    sex: "Female",
    assignedWorker: "Deacon Peter",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Olamide Abdul",
    phoneNumber: "555-678-9123",
    sex: "Female",
    assignedWorker: "Sister Mary",
    contacted: true,
    feedback: "Enthusiastic about joining regular Bible study",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ogar Solomon",
    phoneNumber: "555-789-0123",
    sex: "Male",
    assignedWorker: "Brother Joseph",
    contacted: true,
    feedback: "Seeking guidance for personal issues",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Chinyere",
    phoneNumber: "555-890-1234",
    sex: "Female",
    assignedWorker: "Sister Elizabeth",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Blessing Nuru",
    phoneNumber: "555-901-2345",
    sex: "Female",
    assignedWorker: "Pastor Jonathan",
    contacted: true,
    feedback: "Interested in youth program for children",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Malachy",
    phoneNumber: "555-012-3456",
    sex: "Male",
    assignedWorker: "Deacon Ruth",
    contacted: true,
    feedback: "New to area, looking for church community",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Lazarus",
    phoneNumber: "555-123-3456",
    sex: "Male",
    assignedWorker: "Sister Naomi",
    contacted: true,
    feedback: "Attended worship service, enjoyed music",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Afolabi Oluwatosin",
    phoneNumber: "555-234-4567",
    sex: "Male",
    assignedWorker: "Brother Mark",
    contacted: true,
    feedback: "Interested in men's ministry",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Moshood",
    phoneNumber: "555-345-5678",
    sex: "Male",
    assignedWorker: "Pastor Samuel",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Jennifer",
    phoneNumber: "555-456-6789",
    sex: "Female",
    assignedWorker: "Sister Rebecca",
    contacted: true,
    feedback: "Has theological questions, seeking deeper understanding",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Wisdom",
    phoneNumber: "555-567-7890",
    sex: "Male",
    assignedWorker: "Brother Andrew",
    contacted: true,
    feedback: "Struggling with faith, needs guidance",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Ndum Carine",
    phoneNumber: "555-678-8901",
    sex: "Female",
    assignedWorker: "Deacon Sarah",
    contacted: true,
    feedback: "Attended marriage workshop, seeking counseling",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Joseph Ogbu",
    phoneNumber: "555-789-9012",
    sex: "Male",
    assignedWorker: "Sister Deborah",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Omodele Abayomi",
    phoneNumber: "555-890-0123",
    sex: "Female",
    assignedWorker: "Pastor Timothy",
    contacted: true,
    feedback: "Recently moved to area, looking for spiritual home",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Abraham",
    phoneNumber: "555-901-1234",
    sex: "Male",
    assignedWorker: "Brother Paul",
    contacted: true,
    feedback:
      "Concerned about climate stewardship, interested in faith perspective",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Thomas",
    phoneNumber: "555-012-2345",
    sex: "Male",
    assignedWorker: "Sister Grace",
    contacted: true,
    feedback: "Participated in community cleanup event, interested in church",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Crystabel",
    phoneNumber: "555-123-3456",
    sex: "Female",
    assignedWorker: "Deacon Luke",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Abiodun Olubunkola",
    phoneNumber: "555-234-4567",
    sex: "Female",
    assignedWorker: "Sister Esther",
    contacted: true,
    feedback: "Interested in church's environmental stewardship program",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Comfort Joshua",
    phoneNumber: "555-345-5678",
    sex: "Female",
    assignedWorker: "Pastor Daniel",
    contacted: true,
    feedback: "Works in conservation, seeking spiritual community",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Mr. Ayo",
    phoneNumber: "555-456-6789",
    sex: "Male",
    assignedWorker: "Brother Aaron",
    contacted: true,
    feedback:
      "Attended environmental workshop at church, interested in Bible study",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Ayo",
    phoneNumber: "555-567-7890",
    sex: "Male",
    assignedWorker: "Sister Miriam",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Mr. Ola",
    phoneNumber: "555-678-8901",
    sex: "Male",
    assignedWorker: "Deacon Matthew",
    contacted: true,
    feedback: "Passionate about creation care, seeking church alignment",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Mr. Moses",
    phoneNumber: "555-789-9012",
    sex: "Male",
    assignedWorker: "Pastor Simon",
    contacted: true,
    feedback: "Attended eco-theology discussion, has follow-up questions",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Salome",
    phoneNumber: "555-234-5678",
    sex: "Female",
    assignedWorker: "Sister Rachel",
    contacted: true,
    feedback: "Interested in women's fellowship",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Ruth",
    phoneNumber: "555-345-6789",
    sex: "Female",
    assignedWorker: "Deacon Peter",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Oluseyi",
    phoneNumber: "555-456-7890",
    sex: "Male",
    assignedWorker: "Pastor Michael",
    contacted: true,
    feedback: "Has questions about baptism",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Gabriel",
    phoneNumber: "555-567-8901",
    sex: "Male",
    assignedWorker: "Brother Joseph",
    contacted: true,
    feedback: "Seeking spiritual guidance",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Lucky",
    phoneNumber: "555-678-9012",
    sex: "Male",
    assignedWorker: "Sister Elizabeth",
    contacted: true,
    feedback: "Wants to join the choir",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Kehinde",
    phoneNumber: "555-789-0123",
    sex: "Female",
    assignedWorker: "Pastor Jonathan",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Bisola",
    phoneNumber: "555-890-1234",
    sex: "Female",
    assignedWorker: "Deacon Ruth",
    contacted: true,
    feedback: "Interested in family counseling",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Janet",
    phoneNumber: "555-901-2345",
    sex: "Female",
    assignedWorker: "Sister Naomi",
    contacted: true,
    feedback: "Wants to volunteer for community outreach",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Yusuf",
    phoneNumber: "555-012-3456",
    sex: "Male",
    assignedWorker: "Brother Mark",
    contacted: true,
    feedback: "Seeking interfaith dialogue",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Johnson",
    phoneNumber: "555-123-4567",
    sex: "Male",
    assignedWorker: "Pastor Samuel",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Afin",
    phoneNumber: "555-234-5678",
    sex: "Male",
    assignedWorker: "Sister Rebecca",
    contacted: true,
    feedback: "Interested in youth ministry",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Isaac",
    phoneNumber: "555-345-6789",
    sex: "Male",
    assignedWorker: "Brother Andrew",
    contacted: true,
    feedback: "Seeking Bible study group",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Mattew",
    phoneNumber: "555-456-7890",
    sex: "Male",
    assignedWorker: "Deacon Sarah",
    contacted: true,
    feedback: "Has questions about church doctrine",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Wale & Ishola & Ademola",
    phoneNumber: "555-567-8901",
    sex: "Male",
    assignedWorker: "Sister Deborah",
    contacted: true,
    feedback: "Group of friends interested in men's fellowship",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Donald Atim",
    phoneNumber: "555-678-9012",
    sex: "Male",
    assignedWorker: "Pastor Timothy",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Sunday John",
    phoneNumber: "555-789-0123",
    sex: "Male",
    assignedWorker: "Brother Paul",
    contacted: true,
    feedback: "Wants to join discipleship program",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Micheal Paul",
    phoneNumber: "555-890-1234",
    sex: "Male",
    assignedWorker: "Sister Grace",
    contacted: true,
    feedback: "Seeking prayer support",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "David Lawrence",
    phoneNumber: "555-901-2345",
    sex: "Male",
    assignedWorker: "Deacon Luke",
    contacted: true,
    feedback: "Interested in environmental justice from faith perspective",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "22-Feb-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Abdul",
    phoneNumber: "555-012-3456",
    sex: "Male",
    assignedWorker: "Sister Esther",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Peace",
    phoneNumber: "555-123-4567",
    sex: "Female",
    assignedWorker: "Pastor Daniel",
    contacted: true,
    feedback: "Looking for supportive faith community",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Peter",
    phoneNumber: "555-234-5678",
    sex: "Male",
    assignedWorker: "Brother Aaron",
    contacted: true,
    feedback: "Wants to join church after environmental program",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "John",
    phoneNumber: "555-345-6789",
    sex: "Male",
    assignedWorker: "Sister Miriam",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
  {
    dateOfVisit: "9-Mar-2025",
    formOfEvangelism: "Environment Evangelism",
    name: "Daniel",
    phoneNumber: "555-456-7890",
    sex: "Male",
    assignedWorker: "Deacon Matthew",
    contacted: true,
    feedback: "Interested in children's ministry",
    foundationClass: false,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Godfrey",
    phoneNumber: "555-567-8901",
    sex: "Male",
    assignedWorker: "Pastor Simon",
    contacted: true,
    feedback: "Looking for a church home",
    foundationClass: true,
    counselingClass: false,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Manasseh",
    phoneNumber: "555-678-9012",
    sex: "Male",
    assignedWorker: "Sister Rachel",
    contacted: true,
    feedback: "Wants to learn more about the Bible",
    foundationClass: true,
    counselingClass: true,
  },
  {
    dateOfVisit: "14-Feb-2025",
    formOfEvangelism: "Bus Evangelism",
    name: "Paul Okafor",
    phoneNumber: "555-789-0123",
    sex: "Male",
    assignedWorker: "Deacon Peter",
    contacted: false,
    feedback: "",
    foundationClass: false,
    counselingClass: false,
  },
];
